### ISSUE TITLE
Stupid quest

### ISSUE THREAD

**Issue by ElModdy** [rslindee/dotfiles#1]
Hi,
I'm new to Stow and I'm having difficulties understanding how to manage the dotfiles properly.
My quest is: If you have to add a file, do you create it in the repo and then relaunch stow every time?
I know my question is off topic and I will remove it if you don't want to answare me but I really appreciate any kind of help.

**Comment by rslindee** [comment]
Typically, if I am adding a file to a folder I have stowed/symlinked, I just copy the file to ~/my-stowed-dir/ and it will show up in my dotfiles repo as "new". From there I just add and commit the file in git.
